# Generated by Django 3.2.8 on 2021-10-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categorias',
            field=models.ManyToManyField(to='display.Categoria'),
        ),
    ]
