# Generated by Django 3.2.8 on 2021-10-24 17:33

import display.models.video
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_video_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, help_text='Adicione aqui o vídeo no formato .mp4', null=True, upload_to='videos/', validators=[display.models.video.validate_file_extension], verbose_name='Vídeo'),
        ),
    ]
