# Generated by Django 3.2.8 on 2021-10-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_auto_20211024_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='foto_capa',
            field=models.ImageField(null=True, upload_to='fotos_capa/', verbose_name='Foto de Capa'),
        ),
        migrations.AlterField(
            model_name='video',
            name='categorias',
            field=models.ManyToManyField(to='display.Categoria', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='video',
            name='nome',
            field=models.CharField(max_length=16, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='video',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
